spring:
  application:
    name: WRM_V1
  profiles:
    active: ${DEFAULT_ACTIVE_PROFILE}
  datasource:
    driver-class-name: com.ibm.db2.jcc.DB2Driver
    username: ${DB_AUTH_USERNAME}
    password: ${DB_AUTH_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update

---
spring:
  config:
    activate:
      on-profile: dev,sit
  datasource:
    url : ${DEV_DB_URL}


---
spring:
  config:
    activate:
      on-profile: uat
  datasource:
    url : ${TEST_DB_URL}

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url : ${PROD_DB_URL}

